#Use this file to complete the lab
print("Lab 02, 80 Point Version")
print()
print()
print("Measure today's knowledge", end="")
print("By yesterday's confusion.")
print()
print("Bewildermint + Exposure = Obvious")
print()
print("# ##### #####     ##### ##### # #   # ##### #####")
print("# #   # #   #     #   # #   # # ##  #   #   #")
print("# #   # #   #     ##### #   # # # # #   #   #####")
print("# #   # #   #     #     #   # # #  ##   #       #")
print("# ##### #####     #     ##### # #   #   #   #####")